Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "phalcon-dev"
  config.vm.network "private_network", ip: "192.168.7.3"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  config.vm.post_up_message = "\"Click!\" phalcon environment is ready."
  config.vm.provider "virtualbox" do |vb|
    vb.gui = false
    vb.name = "phalcon-dev"
    vb.memory = 512
    vb.cpus = 1
  end
  config.vm.provision "salt" do |salt|
    salt.install_type = "stable"
    salt.bootstrap_options = "-F -c /tmp/ -P"           # https://github.com/mitchellh/vagrant/issues/5973
    salt.no_minion = false
    salt.minion_config = "minion.yml"
    salt.run_highstate = true
    salt.colorize = true
    salt.log_level = "warning"
    salt.pillar({
      "environment" => "dev",
      "database" => {                                   # unfortunately, there is a replacement, not a merge
        "name" => "click",
        "user" => "click_ro",
        "pass" => "click_ro_pass",
        "host" => "dbro",
        "ip" => "192.168.7.2",
      },
    })
  end
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "saltstack", "/srv"
  config.ssh.forward_agent = true
end
