# -*- mode: ruby -*-
# vi: set ft=ruby :
Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"
  config.vm.hostname = "phalcon"
  config.vm.network "private_network", ip: "192.168.7.3"
  config.vm.network "forwarded_port", guest: 80, host: 8080
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder "saltstack", "/srv"
  config.vm.provision :salt do |salt|
    salt.minion_config = "minion.ini"
    salt.run_highstate = true
    salt.log_level = "warning"
  end
  config.ssh.username = "vagrant"
  config.ssh.password = "vagrant"
  config.ssh.forward_agent = true
  config.ssh.insert_key = true
end
