#!/usr/bin/env php
<?php
/**
 * @author Kamil Samigullin <kamil@samigullin.info>
 */
use Cilex\Application;
use Doctrine\Common\Annotations\AnnotationRegistry;
use Doctrine\DBAL\Migrations\Tools\Console\Command as Migration;
use OctoLab\Cilex\Provider as HelperProvider;

define('ROOT_DIR', dirname(__DIR__));

$loader = require ROOT_DIR . '/vendor/autoload.php';
AnnotationRegistry::registerLoader([$loader, 'loadClass']);

$debug = filter_var(getenv('DEBUG'), FILTER_VALIDATE_BOOLEAN);

$app = new Application('ForestManager', 'alpha');
$app->register(new HelperProvider\ConfigServiceProvider(ROOT_DIR . '/app/config/config.yml', [
    'root_dir' => ROOT_DIR,
]));
$app->register(new HelperProvider\DoctrineServiceProvider(true));
$app->register(new HelperProvider\MonologServiceProvider($debug));
$app->command(new Migration\GenerateCommand());
$app->command(new Migration\MigrateCommand());
$app->command(new Migration\StatusCommand());
$app->command(new Migration\VersionCommand());
$app->run();
